language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - build-tools-21.1.0
    - android-21
    - sys-img-armeabi-v7a-android-21    

before_install:
 - chmod +x gradlew

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a

script: "./gradlew build"
